# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         HTML-Widget-DBIC
version:      0.03
version_from: lib/HTML/Widget/DBIC.pm
installdirs:  site
requires:
    DBIx::Class:                   0
    HTML::Widget:                  1.1
    Test::Simple:                  0.44

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
